# Generated by Django 3.0.4 on 2020-04-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysisapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Dob', models.DateField()),
                ('Gender', models.CharField(max_length=100)),
                ('Mobile', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
